import * as PhosphorIcons from '@phosphor-icons/react'

export interface PhosphorIconEntry {
  name: string
  label: string
  Component: React.ComponentType<{ className?: string; size?: number | string }>
}

function kebabToPascal(str: string): string {
  return str
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('')
}

export function getPhosphorIcon(name: string): PhosphorIconEntry | undefined {
  const pascalName = kebabToPascal(name) + 'Icon'
  const Component = (PhosphorIcons as any)[pascalName]
  if (!Component) return undefined
  return { name, label: name, Component }
}

export function getPhosphorIconComponent(name: string): React.ComponentType<{ className?: string; size?: number | string }> | null {
  const pascalName = kebabToPascal(name) + 'Icon'
  return (PhosphorIcons as any)[pascalName] || null
}

export const SOCIAL_ICONS: PhosphorIconEntry[] = [
  { name: 'github-logo', label: 'GitHub', Component: PhosphorIcons.GithubLogoIcon },
  { name: 'twitter-logo', label: 'Twitter', Component: PhosphorIcons.TwitterLogoIcon },
  { name: 'x-logo', label: 'X', Component: PhosphorIcons.XLogoIcon },
  { name: 'facebook-logo', label: 'Facebook', Component: PhosphorIcons.FacebookLogoIcon },
  { name: 'instagram-logo', label: 'Instagram', Component: PhosphorIcons.InstagramLogoIcon },
  { name: 'linkedin-logo', label: 'LinkedIn', Component: PhosphorIcons.LinkedinLogoIcon },
  { name: 'youtube-logo', label: 'YouTube', Component: PhosphorIcons.YoutubeLogoIcon },
  { name: 'tiktok-logo', label: 'TikTok', Component: PhosphorIcons.TiktokLogoIcon },
  { name: 'whatsapp-logo', label: 'WhatsApp', Component: PhosphorIcons.WhatsappLogoIcon },
  { name: 'discord-logo', label: 'Discord', Component: PhosphorIcons.DiscordLogoIcon },
  { name: 'telegram-logo', label: 'Telegram', Component: PhosphorIcons.TelegramLogoIcon },
  { name: 'reddit-logo', label: 'Reddit', Component: PhosphorIcons.RedditLogoIcon },
  { name: 'pinterest-logo', label: 'Pinterest', Component: PhosphorIcons.PinterestLogoIcon },
  { name: 'snapchat-logo', label: 'Snapchat', Component: PhosphorIcons.SnapchatLogoIcon },
  { name: 'threads-logo', label: 'Threads', Component: PhosphorIcons.ThreadsLogoIcon },
  { name: 'twitch-logo', label: 'Twitch', Component: PhosphorIcons.TwitchLogoIcon },
  { name: 'slack-logo', label: 'Slack', Component: PhosphorIcons.SlackLogoIcon },
  { name: 'mastodon-logo', label: 'Mastodon', Component: PhosphorIcons.MastodonLogoIcon },
]

export const UI_ICONS: PhosphorIconEntry[] = [
  { name: 'graduation-cap', label: 'Graduation', Component: PhosphorIcons.GraduationCapIcon },
  { name: 'student', label: 'Student', Component: PhosphorIcons.StudentIcon },
  { name: 'book-open', label: 'Book', Component: PhosphorIcons.BookOpenIcon },
  { name: 'notebook', label: 'Notebook', Component: PhosphorIcons.NotebookIcon },
  { name: 'certificate', label: 'Certificate', Component: PhosphorIcons.CertificateIcon },
  { name: 'pencil', label: 'Pencil', Component: PhosphorIcons.PencilIcon },
  { name: 'pen-nib', label: 'Pen', Component: PhosphorIcons.PenNibIcon },
  { name: 'ruler', label: 'Ruler', Component: PhosphorIcons.RulerIcon },
  { name: 'calculator', label: 'Calculator', Component: PhosphorIcons.CalculatorIcon },
  { name: 'flask', label: 'Science', Component: PhosphorIcons.FlaskIcon },
  { name: 'test-tube', label: 'Lab', Component: PhosphorIcons.TestTubeIcon },
  { name: 'globe-hemisphere-west', label: 'Globe', Component: PhosphorIcons.GlobeHemisphereWestIcon },
  { name: 'music-note', label: 'Music', Component: PhosphorIcons.MusicNoteIcon },
  { name: 'paint-brush', label: 'Art', Component: PhosphorIcons.PaintBrushIcon },
  { name: 'trophy', label: 'Trophy', Component: PhosphorIcons.TrophyIcon },
  { name: 'medal', label: 'Medal', Component: PhosphorIcons.MedalIcon },
  { name: 'bus', label: 'Bus', Component: PhosphorIcons.BusIcon },
  { name: 'clipboard-text', label: 'Clipboard', Component: PhosphorIcons.ClipboardTextIcon },
  { name: 'file-text', label: 'Report', Component: PhosphorIcons.FileTextIcon },
  { name: 'clock', label: 'Clock', Component: PhosphorIcons.ClockIcon },
  { name: 'envelope', label: 'Mail', Component: PhosphorIcons.EnvelopeIcon },
  { name: 'phone', label: 'Phone', Component: PhosphorIcons.PhoneIcon },
  { name: 'map-pin', label: 'Location', Component: PhosphorIcons.MapPinIcon },
  { name: 'list', label: 'Menu', Component: PhosphorIcons.ListIcon },
  { name: 'x', label: 'Close', Component: PhosphorIcons.XIcon },
  { name: 'check', label: 'Check', Component: PhosphorIcons.CheckIcon },
  { name: 'caret-down', label: 'Chevron Down', Component: PhosphorIcons.CaretDownIcon },
  { name: 'caret-up', label: 'Chevron Up', Component: PhosphorIcons.CaretUpIcon },
  { name: 'caret-right', label: 'Chevron Right', Component: PhosphorIcons.CaretRightIcon },
  { name: 'caret-left', label: 'Chevron Left', Component: PhosphorIcons.CaretLeftIcon },
  { name: 'arrow-right', label: 'Arrow Right', Component: PhosphorIcons.ArrowRightIcon },
  { name: 'arrow-left', label: 'Arrow Left', Component: PhosphorIcons.ArrowLeftIcon },
  { name: 'arrow-up', label: 'Arrow Up', Component: PhosphorIcons.ArrowUpIcon },
  { name: 'arrow-down', label: 'Arrow Down', Component: PhosphorIcons.ArrowDownIcon },
  { name: 'magnifying-glass', label: 'Search', Component: PhosphorIcons.MagnifyingGlassIcon },
  { name: 'bell', label: 'Bell', Component: PhosphorIcons.BellIcon },
  { name: 'gear', label: 'Settings', Component: PhosphorIcons.GearIcon },
  { name: 'heart', label: 'Heart', Component: PhosphorIcons.HeartIcon },
  { name: 'star', label: 'Star', Component: PhosphorIcons.StarIcon },
  { name: 'share-network', label: 'Share', Component: PhosphorIcons.ShareNetworkIcon },
  { name: 'link', label: 'Link', Component: PhosphorIcons.LinkIcon },
  { name: 'copy', label: 'Copy', Component: PhosphorIcons.CopyIcon },
  { name: 'pencil-simple', label: 'Edit', Component: PhosphorIcons.PencilSimpleIcon },
  { name: 'trash', label: 'Delete', Component: PhosphorIcons.TrashIcon },
  { name: 'plus', label: 'Plus', Component: PhosphorIcons.PlusIcon },
  { name: 'minus', label: 'Minus', Component: PhosphorIcons.MinusIcon },
  { name: 'house', label: 'Home', Component: PhosphorIcons.HouseIcon },
  { name: 'user', label: 'User', Component: PhosphorIcons.UserIcon },
  { name: 'users', label: 'Users', Component: PhosphorIcons.UsersIcon },
  { name: 'baby', label: 'Baby', Component: PhosphorIcons.BabyIcon },
  { name: 'cube', label: 'Cube', Component: PhosphorIcons.CubeIcon },
  { name: 'package', label: 'Package', Component: PhosphorIcons.PackageIcon },
  { name: 'image', label: 'Image', Component: PhosphorIcons.ImageIcon },
  { name: 'images', label: 'Images', Component: PhosphorIcons.ImagesIcon },
  { name: 'video', label: 'Video', Component: PhosphorIcons.VideoIcon },
  { name: 'play', label: 'Play', Component: PhosphorIcons.PlayIcon },
  { name: 'image-square', label: 'Gallery', Component: PhosphorIcons.ImageSquareIcon },
  { name: 'folder', label: 'Folder', Component: PhosphorIcons.FolderIcon },
  { name: 'download-simple', label: 'Download', Component: PhosphorIcons.DownloadSimpleIcon },
  { name: 'upload-simple', label: 'Upload', Component: PhosphorIcons.UploadSimpleIcon },
  { name: 'calendar', label: 'Calendar', Component: PhosphorIcons.CalendarIcon },
  { name: 'calendar-blank', label: 'Calendar Alt', Component: PhosphorIcons.CalendarBlankIcon },
  { name: 'alarm', label: 'Alarm', Component: PhosphorIcons.AlarmIcon },
  { name: 'timer', label: 'Timer', Component: PhosphorIcons.TimerIcon },
  { name: 'map-trifold', label: 'Map', Component: PhosphorIcons.MapTrifoldIcon },
  { name: 'navigation-arrow', label: 'Navigate', Component: PhosphorIcons.NavigationArrowIcon },
  { name: 'push-pin', label: 'Pin', Component: PhosphorIcons.PushPinIcon },
  { name: 'tag', label: 'Tag', Component: PhosphorIcons.TagIcon },
  { name: 'credit-card', label: 'Credit Card', Component: PhosphorIcons.CreditCardIcon },
  { name: 'currency-dollar', label: 'Dollar', Component: PhosphorIcons.CurrencyDollarIcon },
  { name: 'percent', label: 'Percent', Component: PhosphorIcons.PercentIcon },
  { name: 'receipt', label: 'Receipt', Component: PhosphorIcons.ReceiptIcon },
  { name: 'shopping-cart', label: 'Cart', Component: PhosphorIcons.ShoppingCartIcon },
  { name: 'storefront', label: 'Store', Component: PhosphorIcons.StorefrontIcon },
  { name: 'bank', label: 'Bank', Component: PhosphorIcons.BankIcon },
  { name: 'wallet', label: 'Wallet', Component: PhosphorIcons.WalletIcon },
  { name: 'lock', label: 'Lock', Component: PhosphorIcons.LockIcon },
  { name: 'lock-open', label: 'Unlock', Component: PhosphorIcons.LockOpenIcon },
  { name: 'key', label: 'Key', Component: PhosphorIcons.KeyIcon },
  { name: 'shield', label: 'Shield', Component: PhosphorIcons.ShieldIcon },
  { name: 'shield-check', label: 'Shield Check', Component: PhosphorIcons.ShieldCheckIcon },
  { name: 'eye', label: 'Eye', Component: PhosphorIcons.EyeIcon },
  { name: 'eye-slash', label: 'Eye Off', Component: PhosphorIcons.EyeSlashIcon },
  { name: 'flag', label: 'Flag', Component: PhosphorIcons.FlagIcon },
  { name: 'bookmark', label: 'Bookmark', Component: PhosphorIcons.BookmarkIcon },
  { name: 'bookmark-simple', label: 'Bookmark Alt', Component: PhosphorIcons.BookmarkSimpleIcon },
  { name: 'chat-circle', label: 'Comment', Component: PhosphorIcons.ChatCircleIcon },
  { name: 'chat-circle-dots', label: 'Comment Dots', Component: PhosphorIcons.ChatCircleDotsIcon },
  { name: 'chat-dots', label: 'Chat', Component: PhosphorIcons.ChatDotsIcon },
  { name: 'megaphone', label: 'Megaphone', Component: PhosphorIcons.MegaphoneIcon },
  { name: 'newspaper', label: 'News', Component: PhosphorIcons.NewspaperIcon },
  { name: 'broadcast', label: 'Broadcast', Component: PhosphorIcons.BroadcastIcon },
  { name: 'wifi-high', label: 'WiFi', Component: PhosphorIcons.WifiHighIcon },
  { name: 'bluetooth', label: 'Bluetooth', Component: PhosphorIcons.BluetoothIcon },
  { name: 'cloud', label: 'Cloud', Component: PhosphorIcons.CloudIcon },
  { name: 'cloud-check', label: 'Cloud Check', Component: PhosphorIcons.CloudCheckIcon },
  { name: 'cloud-arrow-up', label: 'Cloud Upload', Component: PhosphorIcons.CloudArrowUpIcon },
  { name: 'cloud-arrow-down', label: 'Cloud Download', Component: PhosphorIcons.CloudArrowDownIcon },
  { name: 'database', label: 'Database', Component: PhosphorIcons.DatabaseIcon },
  { name: 'hard-drives', label: 'Servers', Component: PhosphorIcons.HardDrivesIcon },
  { name: 'code', label: 'Code', Component: PhosphorIcons.CodeIcon },
  { name: 'terminal', label: 'Terminal', Component: PhosphorIcons.TerminalIcon },
  { name: 'terminal-window', label: 'Terminal Window', Component: PhosphorIcons.TerminalWindowIcon },
  { name: 'cpu', label: 'CPU', Component: PhosphorIcons.CpuIcon },
  { name: 'memory', label: 'Memory', Component: PhosphorIcons.MemoryIcon },
  { name: 'hard-drive', label: 'Hard Drive', Component: PhosphorIcons.HardDriveIcon },
  { name: 'monitor', label: 'Monitor', Component: PhosphorIcons.MonitorIcon },
  { name: 'device-mobile', label: 'Mobile', Component: PhosphorIcons.DeviceMobileIcon },
  { name: 'device-tablet', label: 'Tablet', Component: PhosphorIcons.DeviceTabletIcon },
  { name: 'printer', label: 'Printer', Component: PhosphorIcons.PrinterIcon },
  { name: 'projector-screen', label: 'Projector', Component: PhosphorIcons.ProjectorScreenIcon },
  { name: 'camera', label: 'Camera', Component: PhosphorIcons.CameraIcon },
  { name: 'camera-slash', label: 'Camera Off', Component: PhosphorIcons.CameraSlashIcon },
  { name: 'microphone', label: 'Mic', Component: PhosphorIcons.MicrophoneIcon },
  { name: 'microphone-slash', label: 'Mic Off', Component: PhosphorIcons.MicrophoneSlashIcon },
  { name: 'speaker-high', label: 'Speaker', Component: PhosphorIcons.SpeakerHighIcon },
  { name: 'headphones', label: 'Headphones', Component: PhosphorIcons.HeadphonesIcon },
  { name: 'vinyl-record', label: 'Record', Component: PhosphorIcons.VinylRecordIcon },
  { name: 'music-notes', label: 'Playlist', Component: PhosphorIcons.MusicNotesIcon },
  { name: 'headset', label: 'Headset', Component: PhosphorIcons.HeadsetIcon },
  { name: 'airplane', label: 'Airplane', Component: PhosphorIcons.AirplaneIcon },
  { name: 'airplane-takeoff', label: 'Takeoff', Component: PhosphorIcons.AirplaneTakeoffIcon },
  { name: 'airplane-landing', label: 'Landing', Component: PhosphorIcons.AirplaneLandingIcon },
  { name: 'car', label: 'Car', Component: PhosphorIcons.CarIcon },
  { name: 'van', label: 'Van', Component: PhosphorIcons.VanIcon },
  { name: 'bicycle', label: 'Bicycle', Component: PhosphorIcons.BicycleIcon },
  { name: 'train', label: 'Train', Component: PhosphorIcons.TrainIcon },
  { name: 'train-simple', label: 'Train Alt', Component: PhosphorIcons.TrainSimpleIcon },
  { name: 'boat', label: 'Boat', Component: PhosphorIcons.BoatIcon },
  { name: 'compass', label: 'Compass', Component: PhosphorIcons.CompassIcon },
  { name: 'path', label: 'Path', Component: PhosphorIcons.PathIcon },
  { name: 'identification-card', label: 'ID Card', Component: PhosphorIcons.IdentificationCardIcon },
  { name: 'identification-badge', label: 'Badge', Component: PhosphorIcons.IdentificationBadgeIcon },
  { name: 'translate', label: 'Translate', Component: PhosphorIcons.TranslateIcon },
  { name: 'sun', label: 'Sun', Component: PhosphorIcons.SunIcon },
  { name: 'moon', label: 'Moon', Component: PhosphorIcons.MoonIcon },
  { name: 'cloud-sun', label: 'Partly Sunny', Component: PhosphorIcons.CloudSunIcon },
  { name: 'cloud-moon', label: 'Cloudy Night', Component: PhosphorIcons.CloudMoonIcon },
  { name: 'umbrella', label: 'Umbrella', Component: PhosphorIcons.UmbrellaIcon },
  { name: 'drop', label: 'Drop', Component: PhosphorIcons.DropIcon },
  { name: 'drop-half', label: 'Droplet', Component: PhosphorIcons.DropHalfIcon },
  { name: 'snowflake', label: 'Snow', Component: PhosphorIcons.SnowflakeIcon },
  { name: 'tree', label: 'Tree', Component: PhosphorIcons.TreeIcon },
  { name: 'flower', label: 'Flower', Component: PhosphorIcons.FlowerIcon },
  { name: 'leaf', label: 'Leaf', Component: PhosphorIcons.LeafIcon },
  { name: 'plant', label: 'Plant', Component: PhosphorIcons.PlantIcon },
  { name: 'flower-lotus', label: 'Lotus', Component: PhosphorIcons.FlowerLotusIcon },
  { name: 'paw-print', label: 'Paw', Component: PhosphorIcons.PawPrintIcon },
  { name: 'fish', label: 'Fish', Component: PhosphorIcons.FishIcon },
  { name: 'bird', label: 'Bird', Component: PhosphorIcons.BirdIcon },
  { name: 'butterfly', label: 'Butterfly', Component: PhosphorIcons.ButterflyIcon },
  { name: 'lightning', label: 'Lightning', Component: PhosphorIcons.LightningIcon },
  { name: 'lightning-slash', label: 'Flash', Component: PhosphorIcons.LightningSlashIcon },
  { name: 'fire', label: 'Fire', Component: PhosphorIcons.FireIcon },
  { name: 'flame', label: 'Flame', Component: PhosphorIcons.FlameIcon },
  { name: 'sparkle', label: 'Sparkle', Component: PhosphorIcons.SparkleIcon },
  { name: 'star-four', label: 'Diamond', Component: PhosphorIcons.StarFourIcon },
  { name: 'dice-five', label: 'Dice', Component: PhosphorIcons.DiceFiveIcon },
  { name: 'game-controller', label: 'Game', Component: PhosphorIcons.GameControllerIcon },
  { name: 'puzzle-piece', label: 'Puzzle', Component: PhosphorIcons.PuzzlePieceIcon },
  { name: 'article', label: 'Article', Component: PhosphorIcons.ArticleIcon },
  { name: 'book-open-text', label: 'Book Text', Component: PhosphorIcons.BookOpenTextIcon },
  { name: 'books', label: 'Books', Component: PhosphorIcons.BooksIcon },
  { name: 'stack', label: 'Stack', Component: PhosphorIcons.StackIcon },
  { name: 'stack-simple', label: 'Stack Alt', Component: PhosphorIcons.StackSimpleIcon },
  { name: 'kanban', label: 'Kanban', Component: PhosphorIcons.KanbanIcon },
  { name: 'faders', label: 'Filter', Component: PhosphorIcons.FadersIcon },
  { name: 'funnel', label: 'Funnel', Component: PhosphorIcons.FunnelIcon },
  { name: 'sliders', label: 'Sliders', Component: PhosphorIcons.SlidersIcon },
  { name: 'wrench', label: 'Wrench', Component: PhosphorIcons.WrenchIcon },
  { name: 'hammer', label: 'Hammer', Component: PhosphorIcons.HammerIcon },
  { name: 'screwdriver', label: 'Screwdriver', Component: PhosphorIcons.ScrewdriverIcon },
  { name: 'gear-six', label: 'Gear Alt', Component: PhosphorIcons.GearSixIcon },
  { name: 'lightbulb', label: 'Idea', Component: PhosphorIcons.LightbulbIcon },
  { name: 'lightbulb-filament', label: 'Lightbulb', Component: PhosphorIcons.LightbulbFilamentIcon },
  { name: 'info', label: 'Info', Component: PhosphorIcons.InfoIcon },
  { name: 'question', label: 'Help', Component: PhosphorIcons.QuestionIcon },
  { name: 'warning', label: 'Warning', Component: PhosphorIcons.WarningIcon },
  { name: 'warning-circle', label: 'Alert', Component: PhosphorIcons.WarningCircleIcon },
  { name: 'check-circle', label: 'Check Circle', Component: PhosphorIcons.CheckCircleIcon },
  { name: 'x-circle', label: 'X Circle', Component: PhosphorIcons.XCircleIcon },
  { name: 'arrows-clockwise', label: 'Refresh', Component: PhosphorIcons.ArrowsClockwiseIcon },
  { name: 'arrow-counter-clockwise', label: 'Undo', Component: PhosphorIcons.ArrowCounterClockwiseIcon },
  { name: 'arrows-out', label: 'Expand', Component: PhosphorIcons.ArrowsOutIcon },
  { name: 'arrows-in', label: 'Collapse', Component: PhosphorIcons.ArrowsInIcon },
  { name: 'arrows-merge', label: 'Merge', Component: PhosphorIcons.ArrowsMergeIcon },
  { name: 'arrows-split', label: 'Split', Component: PhosphorIcons.ArrowsSplitIcon },
  { name: 'git-branch', label: 'Branch', Component: PhosphorIcons.GitBranchIcon },
  { name: 'git-commit', label: 'Commit', Component: PhosphorIcons.GitCommitIcon },
  { name: 'git-merge', label: 'Merge Alt', Component: PhosphorIcons.GitMergeIcon },
  { name: 'git-pull-request', label: 'PR', Component: PhosphorIcons.GitPullRequestIcon },
  { name: 'number-circle-one', label: '1', Component: PhosphorIcons.NumberCircleOneIcon },
  { name: 'number-circle-two', label: '2', Component: PhosphorIcons.NumberCircleTwoIcon },
  { name: 'number-circle-three', label: '3', Component: PhosphorIcons.NumberCircleThreeIcon },
  { name: 'number-circle-four', label: '4', Component: PhosphorIcons.NumberCircleFourIcon },
  { name: 'skip-back', label: 'Skip Back', Component: PhosphorIcons.SkipBackIcon },
  { name: 'skip-forward', label: 'Skip Forward', Component: PhosphorIcons.SkipForwardIcon },
]

export const BADGE_ICONS: PhosphorIconEntry[] = [
  { name: 'seal', label: 'Seal', Component: PhosphorIcons.SealIcon },
  { name: 'seal-check', label: 'Seal Check', Component: PhosphorIcons.SealCheckIcon },
  { name: 'crown', label: 'Crown', Component: PhosphorIcons.CrownIcon },
  { name: 'crown-simple', label: 'Crown Alt', Component: PhosphorIcons.CrownSimpleIcon },
  { name: 'thumbs-up', label: 'Like', Component: PhosphorIcons.ThumbsUpIcon },
  { name: 'thumbs-down', label: 'Dislike', Component: PhosphorIcons.ThumbsDownIcon },
  { name: 'hand-waving', label: 'Wave', Component: PhosphorIcons.HandWavingIcon },
  { name: 'hand-palm', label: 'Stop', Component: PhosphorIcons.HandPalmIcon },
  { name: 'hands-clapping', label: 'Clap', Component: PhosphorIcons.HandsClappingIcon },
  { name: 'rocket', label: 'Rocket', Component: PhosphorIcons.RocketIcon },
  { name: 'rocket-launch', label: 'Launch', Component: PhosphorIcons.RocketLaunchIcon },
  { name: 'target', label: 'Target', Component: PhosphorIcons.TargetIcon },
  { name: 'crosshair', label: 'Crosshair', Component: PhosphorIcons.CrosshairIcon },
  { name: 'cursor', label: 'Cursor', Component: PhosphorIcons.CursorIcon },
  { name: 'cursor-click', label: 'Click', Component: PhosphorIcons.CursorClickIcon },
  { name: 'cursor-text', label: 'Text Cursor', Component: PhosphorIcons.CursorTextIcon },
  { name: 'selection', label: 'Selection', Component: PhosphorIcons.SelectionIcon },
  { name: 'selection-all', label: 'Select All', Component: PhosphorIcons.SelectionAllIcon },
  { name: 'text-aa', label: 'Font', Component: PhosphorIcons.TextAaIcon },
  { name: 'text-t', label: 'Text', Component: PhosphorIcons.TextTIcon },
  { name: 'text-h-one', label: 'H1', Component: PhosphorIcons.TextHOneIcon },
  { name: 'text-h-two', label: 'H2', Component: PhosphorIcons.TextHTwoIcon },
  { name: 'text-h-three', label: 'H3', Component: PhosphorIcons.TextHThreeIcon },
  { name: 'text-h-four', label: 'H4', Component: PhosphorIcons.TextHFourIcon },
  { name: 'text-h-five', label: 'H5', Component: PhosphorIcons.TextHFiveIcon },
  { name: 'text-h-six', label: 'H6', Component: PhosphorIcons.TextHSixIcon },
  { name: 'text-b', label: 'Bold', Component: PhosphorIcons.TextBIcon },
  { name: 'text-italic', label: 'Italic', Component: PhosphorIcons.TextItalicIcon },
  { name: 'text-underline', label: 'Underline', Component: PhosphorIcons.TextUnderlineIcon },
  { name: 'text-strikethrough', label: 'Strikethrough', Component: PhosphorIcons.TextStrikethroughIcon },
  { name: 'text-align-left', label: 'Align Left', Component: PhosphorIcons.TextAlignLeftIcon },
  { name: 'text-align-center', label: 'Align Center', Component: PhosphorIcons.TextAlignCenterIcon },
  { name: 'text-align-right', label: 'Align Right', Component: PhosphorIcons.TextAlignRightIcon },
  { name: 'list-bullets', label: 'Bullet List', Component: PhosphorIcons.ListBulletsIcon },
  { name: 'list-numbers', label: 'Number List', Component: PhosphorIcons.ListNumbersIcon },
  { name: 'list-dashes', label: 'Dash List', Component: PhosphorIcons.ListDashesIcon },
  { name: 'highlighter-circle', label: 'Highlight', Component: PhosphorIcons.HighlighterCircleIcon },
  { name: 'textbox', label: 'Textbox', Component: PhosphorIcons.TextboxIcon },
  { name: 'text-columns', label: 'Columns', Component: PhosphorIcons.TextColumnsIcon },
  { name: 'rows', label: 'Rows', Component: PhosphorIcons.RowsIcon },
  { name: 'table', label: 'Table', Component: PhosphorIcons.TableIcon },
  { name: 'chart-bar', label: 'Bar Chart', Component: PhosphorIcons.ChartBarIcon },
  { name: 'chart-line', label: 'Line Chart', Component: PhosphorIcons.ChartLineIcon },
  { name: 'chart-pie', label: 'Pie Chart', Component: PhosphorIcons.ChartPieIcon },
  { name: 'chart-line-up', label: 'Trend Up', Component: PhosphorIcons.ChartLineUpIcon },
  { name: 'chart-line-down', label: 'Trend Down', Component: PhosphorIcons.ChartLineDownIcon },
  { name: 'chart-bar-horizontal', label: 'Horizontal Bar', Component: PhosphorIcons.ChartBarHorizontalIcon },
  { name: 'flow-arrow', label: 'Flow', Component: PhosphorIcons.FlowArrowIcon },
  { name: 'tree-structure', label: 'Tree', Component: PhosphorIcons.TreeStructureIcon },
  { name: 'git-fork', label: 'Fork', Component: PhosphorIcons.GitForkIcon },
  { name: 'binary', label: 'Binary', Component: PhosphorIcons.BinaryIcon },
  { name: 'brackets-curly', label: 'Braces', Component: PhosphorIcons.BracketsCurlyIcon },
  { name: 'angle', label: 'Angle', Component: PhosphorIcons.AngleIcon },
  { name: 'hash', label: 'Hash', Component: PhosphorIcons.HashIcon },
  { name: 'at', label: 'At', Component: PhosphorIcons.AtIcon },
  { name: 'question-mark', label: 'Question', Component: PhosphorIcons.QuestionMarkIcon },
  { name: 'intersect', label: 'Intersect', Component: PhosphorIcons.IntersectIcon },
  { name: 'cube-transparent', label: '3D', Component: PhosphorIcons.CubeTransparentIcon },
  { name: 'polygon', label: 'Polygon', Component: PhosphorIcons.PolygonIcon },
  { name: 'scribble-loop', label: 'Scribble', Component: PhosphorIcons.ScribbleLoopIcon },
  { name: 'sketch-logo', label: 'Sketch', Component: PhosphorIcons.SketchLogoIcon },
  { name: 'figma-logo', label: 'Figma', Component: PhosphorIcons.FigmaLogoIcon },
  { name: 'framer-logo', label: 'Framer', Component: PhosphorIcons.FramerLogoIcon },
  { name: 'notion-logo', label: 'Notion', Component: PhosphorIcons.NotionLogoIcon },
  { name: 'slack-logo', label: 'Slack', Component: PhosphorIcons.SlackLogoIcon },
  { name: 'spotify-logo', label: 'Spotify', Component: PhosphorIcons.SpotifyLogoIcon },
  { name: 'apple-logo', label: 'Apple', Component: PhosphorIcons.AppleLogoIcon },
  { name: 'windows-logo', label: 'Windows', Component: PhosphorIcons.WindowsLogoIcon },
  { name: 'linux-logo', label: 'Linux', Component: PhosphorIcons.LinuxLogoIcon },
  { name: 'android-logo', label: 'Android', Component: PhosphorIcons.AndroidLogoIcon },
  { name: 'app-store-logo', label: 'App Store', Component: PhosphorIcons.AppStoreLogoIcon },
  { name: 'google-play-logo', label: 'Google Play', Component: PhosphorIcons.GooglePlayLogoIcon },
  { name: 'amazon-logo', label: 'Amazon', Component: PhosphorIcons.AmazonLogoIcon },
  { name: 'paypal-logo', label: 'PayPal', Component: PhosphorIcons.PaypalLogoIcon },
  { name: 'stripe-logo', label: 'Stripe', Component: PhosphorIcons.StripeLogoIcon },
  { name: 'bone', label: 'Bone', Component: PhosphorIcons.BoneIcon },
  { name: 'coffee', label: 'Coffee', Component: PhosphorIcons.CoffeeIcon },
  { name: 'bowl-food', label: 'Food', Component: PhosphorIcons.BowlFoodIcon },
  { name: 'cookie', label: 'Cookie', Component: PhosphorIcons.CookieIcon },
  { name: 'first-aid', label: 'First Aid', Component: PhosphorIcons.FirstAidIcon },
  { name: 'heartbeat', label: 'Heartbeat', Component: PhosphorIcons.HeartbeatIcon },
  { name: 'first-aid-kit', label: 'Med Kit', Component: PhosphorIcons.FirstAidKitIcon },
  { name: 'syringe', label: 'Syringe', Component: PhosphorIcons.SyringeIcon },
  { name: 'pill', label: 'Pill', Component: PhosphorIcons.PillIcon },
  { name: 'thermometer', label: 'Thermometer', Component: PhosphorIcons.ThermometerIcon },
  { name: 'barbell', label: 'Gym', Component: PhosphorIcons.BarbellIcon },
  { name: 'person-simple-run', label: 'Run', Component: PhosphorIcons.PersonSimpleRunIcon },
  { name: 'person-simple-walk', label: 'Walk', Component: PhosphorIcons.PersonSimpleWalkIcon },
  { name: 'swimming-pool', label: 'Pool', Component: PhosphorIcons.SwimmingPoolIcon },
  { name: 'volleyball', label: 'Volleyball', Component: PhosphorIcons.VolleyballIcon },
  { name: 'basketball', label: 'Basketball', Component: PhosphorIcons.BasketballIcon },
  { name: 'soccer-ball', label: 'Soccer', Component: PhosphorIcons.SoccerBallIcon },
  { name: 'football', label: 'Football', Component: PhosphorIcons.FootballIcon },
  { name: 'tennis-ball', label: 'Tennis', Component: PhosphorIcons.TennisBallIcon },
  { name: 'ping-pong', label: 'Ping Pong', Component: PhosphorIcons.PingPongIcon },
  { name: 'book-bookmark', label: 'Reading', Component: PhosphorIcons.BookBookmarkIcon },
  { name: 'exam', label: 'Exam', Component: PhosphorIcons.ExamIcon },
  { name: 'chalkboard-teacher', label: 'Teaching', Component: PhosphorIcons.ChalkboardTeacherIcon },
]
