export interface PhosphorIconEntry {
  name: string
  label: string
  icon: string
}

export const SOCIAL_ICONS: PhosphorIconEntry[] = [
  { name: 'github-logo', label: 'GitHub', icon: 'GithubLogo' },
  { name: 'twitter-logo', label: 'Twitter', icon: 'TwitterLogo' },
  { name: 'x-logo', label: 'X', icon: 'XLogo' },
  { name: 'facebook-logo', label: 'Facebook', icon: 'FacebookLogo' },
  { name: 'instagram-logo', label: 'Instagram', icon: 'InstagramLogo' },
  { name: 'linkedin-logo', label: 'LinkedIn', icon: 'LinkedinLogo' },
  { name: 'youtube-logo', label: 'YouTube', icon: 'YoutubeLogo' },
  { name: 'tiktok-logo', label: 'TikTok', icon: 'TiktokLogo' },
  { name: 'whatsapp-logo', label: 'WhatsApp', icon: 'WhatsappLogo' },
  { name: 'discord-logo', label: 'Discord', icon: 'DiscordLogo' },
  { name: 'telegram-logo', label: 'Telegram', icon: 'TelegramLogo' },
  { name: 'reddit-logo', label: 'Reddit', icon: 'RedditLogo' },
  { name: 'pinterest-logo', label: 'Pinterest', icon: 'PinterestLogo' },
  { name: 'snapchat-logo', label: 'Snapchat', icon: 'SnapchatLogo' },
  { name: 'threads-logo', label: 'Threads', icon: 'ThreadsLogo' },
  { name: 'twitch-logo', label: 'Twitch', icon: 'TwitchLogo' },
  { name: 'slack-logo', label: 'Slack', icon: 'SlackLogo' },
  { name: 'mastodon-logo', label: 'Mastodon', icon: 'MastodonLogo' },
]

export const UI_ICONS: PhosphorIconEntry[] = [
  { name: 'graduation-cap', label: 'Graduation', icon: 'GraduationCap' },
  { name: 'student', label: 'Student', icon: 'Student' },
  { name: 'book-open', label: 'Book', icon: 'BookOpen' },
  { name: 'notebook', label: 'Notebook', icon: 'Notebook' },
  { name: 'certificate', label: 'Certificate', icon: 'Certificate' },
  { name: 'pencil', label: 'Pencil', icon: 'Pencil' },
  { name: 'pen-nib', label: 'Pen', icon: 'PenNib' },
  { name: 'ruler', label: 'Ruler', icon: 'Ruler' },
  { name: 'calculator', label: 'Calculator', icon: 'Calculator' },
  { name: 'flask', label: 'Science', icon: 'Flask' },
  { name: 'test-tube', label: 'Lab', icon: 'TestTube' },
  { name: 'globe-hemisphere-west', label: 'Globe', icon: 'GlobeHemisphereWest' },
  { name: 'music-note', label: 'Music', icon: 'MusicNote' },
  { name: 'paint-brush', label: 'Art', icon: 'PaintBrush' },
  { name: 'trophy', label: 'Trophy', icon: 'Trophy' },
  { name: 'medal', label: 'Medal', icon: 'Medal' },
  { name: 'bus', label: 'Bus', icon: 'Bus' },
  { name: 'clipboard-text', label: 'Clipboard', icon: 'ClipboardText' },
  { name: 'file-text', label: 'Report', icon: 'FileText' },
  { name: 'clock', label: 'Clock', icon: 'Clock' },
  { name: 'envelope', label: 'Mail', icon: 'Envelope' },
  { name: 'phone', label: 'Phone', icon: 'Phone' },
  { name: 'map-pin', label: 'Location', icon: 'MapPin' },
  { name: 'list', label: 'Menu', icon: 'List' },
  { name: 'x', label: 'Close', icon: 'X' },
  { name: 'check', label: 'Check', icon: 'Check' },
  { name: 'caret-down', label: 'Chevron Down', icon: 'CaretDown' },
  { name: 'caret-up', label: 'Chevron Up', icon: 'CaretUp' },
  { name: 'caret-right', label: 'Chevron Right', icon: 'CaretRight' },
  { name: 'caret-left', label: 'Chevron Left', icon: 'CaretLeft' },
  { name: 'arrow-right', label: 'Arrow Right', icon: 'ArrowRight' },
  { name: 'arrow-left', label: 'Arrow Left', icon: 'ArrowLeft' },
  { name: 'arrow-up', label: 'Arrow Up', icon: 'ArrowUp' },
  { name: 'arrow-down', label: 'Arrow Down', icon: 'ArrowDown' },
  { name: 'magnifying-glass', label: 'Search', icon: 'MagnifyingGlass' },
  { name: 'bell', label: 'Bell', icon: 'Bell' },
  { name: 'gear', label: 'Settings', icon: 'Gear' },
  { name: 'heart', label: 'Heart', icon: 'Heart' },
  { name: 'star', label: 'Star', icon: 'Star' },
  { name: 'share-network', label: 'Share', icon: 'ShareNetwork' },
  { name: 'link', label: 'Link', icon: 'Link' },
  { name: 'copy', label: 'Copy', icon: 'Copy' },
  { name: 'pencil-simple', label: 'Edit', icon: 'PencilSimple' },
  { name: 'trash', label: 'Delete', icon: 'Trash' },
  { name: 'plus', label: 'Plus', icon: 'Plus' },
  { name: 'minus', label: 'Minus', icon: 'Minus' },
  { name: 'house', label: 'Home', icon: 'House' },
  { name: 'user', label: 'User', icon: 'User' },
  { name: 'users', label: 'Users', icon: 'Users' },
  { name: 'baby', label: 'Baby', icon: 'Baby' },
  { name: 'cube', label: 'Cube', icon: 'Cube' },
  { name: 'package', label: 'Package', icon: 'Package' },
  { name: 'image', label: 'Image', icon: 'Image' },
  { name: 'images', label: 'Images', icon: 'Images' },
  { name: 'video', label: 'Video', icon: 'Video' },
  { name: 'play', label: 'Play', icon: 'Play' },
  { name: 'image-square', label: 'Gallery', icon: 'ImageSquare' },
  { name: 'folder', label: 'Folder', icon: 'Folder' },
  { name: 'download-simple', label: 'Download', icon: 'DownloadSimple' },
  { name: 'upload-simple', label: 'Upload', icon: 'UploadSimple' },
  { name: 'calendar', label: 'Calendar', icon: 'Calendar' },
  { name: 'calendar-blank', label: 'Calendar Alt', icon: 'CalendarBlank' },
  { name: 'alarm', label: 'Alarm', icon: 'Alarm' },
  { name: 'timer', label: 'Timer', icon: 'Timer' },
  { name: 'map-trifold', label: 'Map', icon: 'MapTrifold' },
  { name: 'navigation-arrow', label: 'Navigate', icon: 'NavigationArrow' },
  { name: 'push-pin', label: 'Pin', icon: 'PushPin' },
  { name: 'tag', label: 'Tag', icon: 'Tag' },
  { name: 'credit-card', label: 'Credit Card', icon: 'CreditCard' },
  { name: 'currency-dollar', label: 'Dollar', icon: 'CurrencyDollar' },
  { name: 'percent', label: 'Percent', icon: 'Percent' },
  { name: 'receipt', label: 'Receipt', icon: 'Receipt' },
  { name: 'shopping-cart', label: 'Cart', icon: 'ShoppingCart' },
  { name: 'storefront', label: 'Store', icon: 'Storefront' },
  { name: 'bank', label: 'Bank', icon: 'Bank' },
  { name: 'wallet', label: 'Wallet', icon: 'Wallet' },
  { name: 'lock', label: 'Lock', icon: 'Lock' },
  { name: 'lock-open', label: 'Unlock', icon: 'LockOpen' },
  { name: 'key', label: 'Key', icon: 'Key' },
  { name: 'shield', label: 'Shield', icon: 'Shield' },
  { name: 'shield-check', label: 'Shield Check', icon: 'ShieldCheck' },
  { name: 'eye', label: 'Eye', icon: 'Eye' },
  { name: 'eye-slash', label: 'Eye Off', icon: 'EyeSlash' },
  { name: 'flag', label: 'Flag', icon: 'Flag' },
  { name: 'bookmark', label: 'Bookmark', icon: 'Bookmark' },
  { name: 'bookmark-simple', label: 'Bookmark Alt', icon: 'BookmarkSimple' },
  { name: 'chat-circle', label: 'Comment', icon: 'ChatCircle' },
  { name: 'chat-circle-dots', label: 'Comment Dots', icon: 'ChatCircleDots' },
  { name: 'chat-dots', label: 'Chat', icon: 'ChatDots' },
  { name: 'megaphone', label: 'Megaphone', icon: 'Megaphone' },
  { name: 'newspaper', label: 'News', icon: 'Newspaper' },
  { name: 'broadcast', label: 'Broadcast', icon: 'Broadcast' },
  { name: 'wifi-high', label: 'WiFi', icon: 'WifiHigh' },
  { name: 'bluetooth', label: 'Bluetooth', icon: 'Bluetooth' },
  { name: 'cloud', label: 'Cloud', icon: 'Cloud' },
  { name: 'cloud-check', label: 'Cloud Check', icon: 'CloudCheck' },
  { name: 'cloud-arrow-up', label: 'Cloud Upload', icon: 'CloudArrowUp' },
  { name: 'cloud-arrow-down', label: 'Cloud Download', icon: 'CloudArrowDown' },
  { name: 'database', label: 'Database', icon: 'Database' },
  { name: 'hard-drives', label: 'Servers', icon: 'HardDrives' },
  { name: 'code', label: 'Code', icon: 'Code' },
  { name: 'terminal', label: 'Terminal', icon: 'Terminal' },
  { name: 'terminal-window', label: 'Terminal Window', icon: 'TerminalWindow' },
  { name: 'cpu', label: 'CPU', icon: 'Cpu' },
  { name: 'memory', label: 'Memory', icon: 'Memory' },
  { name: 'hard-drive', label: 'Hard Drive', icon: 'HardDrive' },
  { name: 'monitor', label: 'Monitor', icon: 'Monitor' },
  { name: 'device-mobile', label: 'Mobile', icon: 'DeviceMobile' },
  { name: 'device-tablet', label: 'Tablet', icon: 'DeviceTablet' },
  { name: 'printer', label: 'Printer', icon: 'Printer' },
  { name: 'projector-screen', label: 'Projector', icon: 'ProjectorScreen' },
  { name: 'camera', label: 'Camera', icon: 'Camera' },
  { name: 'camera-slash', label: 'Camera Off', icon: 'CameraSlash' },
  { name: 'microphone', label: 'Mic', icon: 'Microphone' },
  { name: 'microphone-slash', label: 'Mic Off', icon: 'MicrophoneSlash' },
  { name: 'speaker-high', label: 'Speaker', icon: 'SpeakerHigh' },
  { name: 'headphones', label: 'Headphones', icon: 'Headphones' },
  { name: 'vinyl-record', label: 'Record', icon: 'VinylRecord' },
  { name: 'music-notes', label: 'Playlist', icon: 'MusicNotes' },
  { name: 'headset', label: 'Headset', icon: 'Headset' },
  { name: 'airplane', label: 'Airplane', icon: 'Airplane' },
  { name: 'airplane-takeoff', label: 'Takeoff', icon: 'AirplaneTakeoff' },
  { name: 'airplane-landing', label: 'Landing', icon: 'AirplaneLanding' },
  { name: 'car', label: 'Car', icon: 'Car' },
  { name: 'van', label: 'Van', icon: 'Van' },
  { name: 'bicycle', label: 'Bicycle', icon: 'Bicycle' },
  { name: 'train', label: 'Train', icon: 'Train' },
  { name: 'train-simple', label: 'Train Alt', icon: 'TrainSimple' },
  { name: 'boat', label: 'Boat', icon: 'Boat' },
  { name: 'compass', label: 'Compass', icon: 'Compass' },
  { name: 'path', label: 'Path', icon: 'Path' },
  { name: 'identification-card', label: 'ID Card', icon: 'IdentificationCard' },
  { name: 'identification-badge', label: 'Badge', icon: 'IdentificationBadge' },
  { name: 'translate', label: 'Translate', icon: 'Translate' },
  { name: 'sun', label: 'Sun', icon: 'Sun' },
  { name: 'moon', label: 'Moon', icon: 'Moon' },
  { name: 'cloud-sun', label: 'Partly Sunny', icon: 'CloudSun' },
  { name: 'cloud-moon', label: 'Cloudy Night', icon: 'CloudMoon' },
  { name: 'umbrella', label: 'Umbrella', icon: 'Umbrella' },
  { name: 'drop', label: 'Drop', icon: 'Drop' },
  { name: 'drop-half', label: 'Droplet', icon: 'DropHalf' },
  { name: 'snowflake', label: 'Snow', icon: 'Snowflake' },
  { name: 'tree', label: 'Tree', icon: 'Tree' },
  { name: 'flower', label: 'Flower', icon: 'Flower' },
  { name: 'leaf', label: 'Leaf', icon: 'Leaf' },
  { name: 'plant', label: 'Plant', icon: 'Plant' },
  { name: 'flower-lotus', label: 'Lotus', icon: 'FlowerLotus' },
  { name: 'paw-print', label: 'Paw', icon: 'PawPrint' },
  { name: 'fish', label: 'Fish', icon: 'Fish' },
  { name: 'bird', label: 'Bird', icon: 'Bird' },
  { name: 'butterfly', label: 'Butterfly', icon: 'Butterfly' },
  { name: 'lightning', label: 'Lightning', icon: 'Lightning' },
  { name: 'lightning-slash', label: 'Flash', icon: 'LightningSlash' },
  { name: 'fire', label: 'Fire', icon: 'Fire' },
  { name: 'flame', label: 'Flame', icon: 'Flame' },
  { name: 'sparkle', label: 'Sparkle', icon: 'Sparkle' },
  { name: 'star-four', label: 'Diamond', icon: 'StarFour' },
  { name: 'dice-five', label: 'Dice', icon: 'DiceFive' },
  { name: 'game-controller', label: 'Game', icon: 'GameController' },
  { name: 'puzzle-piece', label: 'Puzzle', icon: 'PuzzlePiece' },
  { name: 'article', label: 'Article', icon: 'Article' },
  { name: 'book-open-text', label: 'Book Text', icon: 'BookOpenText' },
  { name: 'books', label: 'Books', icon: 'Books' },
  { name: 'stack', label: 'Stack', icon: 'Stack' },
  { name: 'stack-simple', label: 'Stack Alt', icon: 'StackSimple' },
  { name: 'kanban', label: 'Kanban', icon: 'Kanban' },
  { name: 'faders', label: 'Filter', icon: 'Faders' },
  { name: 'funnel', label: 'Funnel', icon: 'Funnel' },
  { name: 'sliders', label: 'Sliders', icon: 'Sliders' },
  { name: 'wrench', label: 'Wrench', icon: 'Wrench' },
  { name: 'hammer', label: 'Hammer', icon: 'Hammer' },
  { name: 'screwdriver', label: 'Screwdriver', icon: 'Screwdriver' },
  { name: 'gear-six', label: 'Gear Alt', icon: 'GearSix' },
  { name: 'lightbulb', label: 'Idea', icon: 'Lightbulb' },
  { name: 'lightbulb-filament', label: 'Lightbulb', icon: 'LightbulbFilament' },
  { name: 'info', label: 'Info', icon: 'Info' },
  { name: 'question', label: 'Help', icon: 'Question' },
  { name: 'warning', label: 'Warning', icon: 'Warning' },
  { name: 'warning-circle', label: 'Alert', icon: 'WarningCircle' },
  { name: 'check-circle', label: 'Check Circle', icon: 'CheckCircle' },
  { name: 'x-circle', label: 'X Circle', icon: 'XCircle' },
  { name: 'arrows-clockwise', label: 'Refresh', icon: 'ArrowsClockwise' },
  { name: 'arrow-counter-clockwise', label: 'Undo', icon: 'ArrowCounterClockwise' },
  { name: 'arrows-out', label: 'Expand', icon: 'ArrowsOut' },
  { name: 'arrows-in', label: 'Collapse', icon: 'ArrowsIn' },
  { name: 'arrows-merge', label: 'Merge', icon: 'ArrowsMerge' },
  { name: 'arrows-split', label: 'Split', icon: 'ArrowsSplit' },
  { name: 'git-branch', label: 'Branch', icon: 'GitBranch' },
  { name: 'git-commit', label: 'Commit', icon: 'GitCommit' },
  { name: 'git-merge', label: 'Merge Alt', icon: 'GitMerge' },
  { name: 'git-pull-request', label: 'PR', icon: 'GitPullRequest' },
  { name: 'number-circle-one', label: '1', icon: 'NumberCircleOne' },
  { name: 'number-circle-two', label: '2', icon: 'NumberCircleTwo' },
  { name: 'number-circle-three', label: '3', icon: 'NumberCircleThree' },
  { name: 'number-circle-four', label: '4', icon: 'NumberCircleFour' },
  { name: 'skip-back', label: 'Skip Back', icon: 'SkipBack' },
  { name: 'skip-forward', label: 'Skip Forward', icon: 'SkipForward' },
]

export const BADGE_ICONS: PhosphorIconEntry[] = [
  { name: 'seal', label: 'Seal', icon: 'Seal' },
  { name: 'seal-check', label: 'Seal Check', icon: 'SealCheck' },
  { name: 'crown', label: 'Crown', icon: 'Crown' },
  { name: 'crown-simple', label: 'Crown Alt', icon: 'CrownSimple' },
  { name: 'thumbs-up', label: 'Like', icon: 'ThumbsUp' },
  { name: 'thumbs-down', label: 'Dislike', icon: 'ThumbsDown' },
  { name: 'hand-waving', label: 'Wave', icon: 'HandWaving' },
  { name: 'hand-palm', label: 'Stop', icon: 'HandPalm' },
  { name: 'hands-clapping', label: 'Clap', icon: 'HandsClapping' },
  { name: 'rocket', label: 'Rocket', icon: 'Rocket' },
  { name: 'rocket-launch', label: 'Launch', icon: 'RocketLaunch' },
  { name: 'target', label: 'Target', icon: 'Target' },
  { name: 'crosshair', label: 'Crosshair', icon: 'Crosshair' },
  { name: 'cursor', label: 'Cursor', icon: 'Cursor' },
  { name: 'cursor-click', label: 'Click', icon: 'CursorClick' },
  { name: 'cursor-text', label: 'Text Cursor', icon: 'CursorText' },
  { name: 'selection', label: 'Selection', icon: 'Selection' },
  { name: 'selection-all', label: 'Select All', icon: 'SelectionAll' },
  { name: 'text-aa', label: 'Font', icon: 'TextAa' },
  { name: 'text-t', label: 'Text', icon: 'TextT' },
  { name: 'text-h-one', label: 'H1', icon: 'TextHOne' },
  { name: 'text-h-two', label: 'H2', icon: 'TextHTwo' },
  { name: 'text-h-three', label: 'H3', icon: 'TextHThree' },
  { name: 'text-h-four', label: 'H4', icon: 'TextHFour' },
  { name: 'text-h-five', label: 'H5', icon: 'TextHFive' },
  { name: 'text-h-six', label: 'H6', icon: 'TextHSix' },
  { name: 'text-b', label: 'Bold', icon: 'TextB' },
  { name: 'text-italic', label: 'Italic', icon: 'TextItalic' },
  { name: 'text-underline', label: 'Underline', icon: 'TextUnderline' },
  { name: 'text-strikethrough', label: 'Strikethrough', icon: 'TextStrikethrough' },
  { name: 'text-align-left', label: 'Align Left', icon: 'TextAlignLeft' },
  { name: 'text-align-center', label: 'Align Center', icon: 'TextAlignCenter' },
  { name: 'text-align-right', label: 'Align Right', icon: 'TextAlignRight' },
  { name: 'list-bullets', label: 'Bullet List', icon: 'ListBullets' },
  { name: 'list-numbers', label: 'Number List', icon: 'ListNumbers' },
  { name: 'list-dashes', label: 'Dash List', icon: 'ListDashes' },
  { name: 'highlighter-circle', label: 'Highlight', icon: 'HighlighterCircle' },
  { name: 'textbox', label: 'Textbox', icon: 'Textbox' },
  { name: 'text-columns', label: 'Columns', icon: 'TextColumns' },
  { name: 'rows', label: 'Rows', icon: 'Rows' },
  { name: 'table', label: 'Table', icon: 'Table' },
  { name: 'chart-bar', label: 'Bar Chart', icon: 'ChartBar' },
  { name: 'chart-line', label: 'Line Chart', icon: 'ChartLine' },
  { name: 'chart-pie', label: 'Pie Chart', icon: 'ChartPie' },
  { name: 'chart-line-up', label: 'Trend Up', icon: 'ChartLineUp' },
  { name: 'chart-line-down', label: 'Trend Down', icon: 'ChartLineDown' },
  { name: 'chart-bar-horizontal', label: 'Horizontal Bar', icon: 'ChartBarHorizontal' },
  { name: 'flow-arrow', label: 'Flow', icon: 'FlowArrow' },
  { name: 'tree-structure', label: 'Tree', icon: 'TreeStructure' },
  { name: 'git-fork', label: 'Fork', icon: 'GitFork' },
  { name: 'binary', label: 'Binary', icon: 'Binary' },
  { name: 'brackets-curly', label: 'Braces', icon: 'BracketsCurly' },
  { name: 'angle', label: 'Angle', icon: 'Angle' },
  { name: 'hash', label: 'Hash', icon: 'Hash' },
  { name: 'at', label: 'At', icon: 'At' },
  { name: 'question-mark', label: 'Question', icon: 'QuestionMark' },
  { name: 'intersect', label: 'Intersect', icon: 'Intersect' },
  { name: 'cube-transparent', label: '3D', icon: 'CubeTransparent' },
  { name: 'polygon', label: 'Polygon', icon: 'Polygon' },
  { name: 'scribble-loop', label: 'Scribble', icon: 'ScribbleLoop' },
  { name: 'sketch-logo', label: 'Sketch', icon: 'SketchLogo' },
  { name: 'figma-logo', label: 'Figma', icon: 'FigmaLogo' },
  { name: 'framer-logo', label: 'Framer', icon: 'FramerLogo' },
  { name: 'notion-logo', label: 'Notion', icon: 'NotionLogo' },
  { name: 'slack-logo', label: 'Slack', icon: 'SlackLogo' },
  { name: 'spotify-logo', label: 'Spotify', icon: 'SpotifyLogo' },
  { name: 'apple-logo', label: 'Apple', icon: 'AppleLogo' },
  { name: 'windows-logo', label: 'Windows', icon: 'WindowsLogo' },
  { name: 'linux-logo', label: 'Linux', icon: 'LinuxLogo' },
  { name: 'android-logo', label: 'Android', icon: 'AndroidLogo' },
  { name: 'app-store-logo', label: 'App Store', icon: 'AppStoreLogo' },
  { name: 'google-play-logo', label: 'Google Play', icon: 'GooglePlayLogo' },
  { name: 'amazon-logo', label: 'Amazon', icon: 'AmazonLogo' },
  { name: 'paypal-logo', label: 'PayPal', icon: 'PaypalLogo' },
  { name: 'stripe-logo', label: 'Stripe', icon: 'StripeLogo' },
  { name: 'bone', label: 'Bone', icon: 'Bone' },
  { name: 'coffee', label: 'Coffee', icon: 'Coffee' },
  { name: 'bowl-food', label: 'Food', icon: 'BowlFood' },
  { name: 'cookie', label: 'Cookie', icon: 'Cookie' },
  { name: 'first-aid', label: 'First Aid', icon: 'FirstAid' },
  { name: 'heartbeat', label: 'Heartbeat', icon: 'Heartbeat' },
  { name: 'first-aid-kit', label: 'Med Kit', icon: 'FirstAidKit' },
  { name: 'syringe', label: 'Syringe', icon: 'Syringe' },
  { name: 'pill', label: 'Pill', icon: 'Pill' },
  { name: 'thermometer', label: 'Thermometer', icon: 'Thermometer' },
  { name: 'barbell', label: 'Gym', icon: 'Barbell' },
  { name: 'person-simple-run', label: 'Run', icon: 'PersonSimpleRun' },
  { name: 'person-simple-walk', label: 'Walk', icon: 'PersonSimpleWalk' },
  { name: 'swimming-pool', label: 'Pool', icon: 'SwimmingPool' },
  { name: 'volleyball', label: 'Volleyball', icon: 'Volleyball' },
  { name: 'basketball', label: 'Basketball', icon: 'Basketball' },
  { name: 'soccer-ball', label: 'Soccer', icon: 'SoccerBall' },
  { name: 'football', label: 'Football', icon: 'Football' },
  { name: 'tennis-ball', label: 'Tennis', icon: 'TennisBall' },
  { name: 'ping-pong', label: 'Ping Pong', icon: 'PingPong' },
  { name: 'book-bookmark', label: 'Reading', icon: 'BookBookmark' },
  { name: 'exam', label: 'Exam', icon: 'Exam' },
  { name: 'chalkboard-teacher', label: 'Teaching', icon: 'ChalkboardTeacher' },
]
